"Name: \PR:SAPMM06E\FO:PREISFINDUNG_PRUEFEN\SE:BEGIN\EI
ENHANCEMENT 0 ZEIMM_PREISFINDUNG_PRUEFEN.
*DATA LV_KONDERR TYPE XFELD.
*IMPORT LV_KONDERR FROM MEMORY ID 'ZMM_KONDERR'.
*IF NOT LV_KONDERR IS INITIAL.
*  CLEAR KONDERR.
*ENDIF.
ENDENHANCEMENT.
