"Name: \PR:SAPLMEPO\FO:GET_ITEM_FROM_POT\SE:BEGIN\EI
ENHANCEMENT 0 ZEIMM_LMEPOF2E.
*DATA LV_KONDERR TYPE XFELD.
*IMPORT LV_KONDERR FROM MEMORY ID 'ZMM_KONDERR'.
*IF NOT LV_KONDERR IS INITIAL.
*  CLEAR KONDERR.
*ENDIF.
ENDENHANCEMENT.
