"Name: \PR:SAPLMEREQ\TY:LCL_REQ_ITEM\IN:IF_PURCHASE_REQUISITION_ITEM\ME:SET_DATA\SE:END\EI
ENHANCEMENT 0 ZEIMM_ITEM_COPIA_LIMPAR_CAMPO.
  IF my_data_input_buffer IS NOT INITIAL.
   CLEAR ls_buffer-data-zz1_statu.
   MODIFY my_data_input_buffer FROM ls_buffer INDEX l_index.
  ENDIF.
ENDENHANCEMENT.
