*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVMM_MAP_COND...................................*
FORM GET_DATA_ZVMM_MAP_COND.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTMM_MAP_COND WHERE
(VIM_WHERETAB) .
    CLEAR ZVMM_MAP_COND .
ZVMM_MAP_COND-MANDT =
ZTMM_MAP_COND-MANDT .
ZVMM_MAP_COND-GRUPO =
ZTMM_MAP_COND-GRUPO .
ZVMM_MAP_COND-KSCHL =
ZTMM_MAP_COND-KSCHL .
ZVMM_MAP_COND-METODO =
ZTMM_MAP_COND-METODO .
ZVMM_MAP_COND-CALCULA =
ZTMM_MAP_COND-CALCULA .
    SELECT SINGLE * FROM T685 WHERE
KVEWE = 'A' AND
KAPPL = 'TX' AND
KSCHL = ZTMM_MAP_COND-KSCHL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T685T WHERE
KVEWE = T685-KVEWE AND
KAPPL = T685-KAPPL AND
KSCHL = T685-KSCHL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVMM_MAP_COND-VTEXT =
T685T-VTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVMM_MAP_COND.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVMM_MAP_COND .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVMM_MAP_COND.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVMM_MAP_COND-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTMM_MAP_COND WHERE
  GRUPO = ZVMM_MAP_COND-GRUPO AND
  KSCHL = ZVMM_MAP_COND-KSCHL .
    IF SY-SUBRC = 0.
    DELETE ZTMM_MAP_COND .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTMM_MAP_COND WHERE
  GRUPO = ZVMM_MAP_COND-GRUPO AND
  KSCHL = ZVMM_MAP_COND-KSCHL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTMM_MAP_COND.
    ENDIF.
ZTMM_MAP_COND-MANDT =
ZVMM_MAP_COND-MANDT .
ZTMM_MAP_COND-GRUPO =
ZVMM_MAP_COND-GRUPO .
ZTMM_MAP_COND-KSCHL =
ZVMM_MAP_COND-KSCHL .
ZTMM_MAP_COND-METODO =
ZVMM_MAP_COND-METODO .
ZTMM_MAP_COND-CALCULA =
ZVMM_MAP_COND-CALCULA .
    IF SY-SUBRC = 0.
    UPDATE ZTMM_MAP_COND ##WARN_OK.
    ELSE.
    INSERT ZTMM_MAP_COND .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVMM_MAP_COND-UPD_FLAG,
STATUS_ZVMM_MAP_COND-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVMM_MAP_COND.
  SELECT SINGLE * FROM ZTMM_MAP_COND WHERE
GRUPO = ZVMM_MAP_COND-GRUPO AND
KSCHL = ZVMM_MAP_COND-KSCHL .
ZVMM_MAP_COND-MANDT =
ZTMM_MAP_COND-MANDT .
ZVMM_MAP_COND-GRUPO =
ZTMM_MAP_COND-GRUPO .
ZVMM_MAP_COND-KSCHL =
ZTMM_MAP_COND-KSCHL .
ZVMM_MAP_COND-METODO =
ZTMM_MAP_COND-METODO .
ZVMM_MAP_COND-CALCULA =
ZTMM_MAP_COND-CALCULA .
    SELECT SINGLE * FROM T685 WHERE
KVEWE = 'A' AND
KAPPL = 'TX' AND
KSCHL = ZTMM_MAP_COND-KSCHL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T685T WHERE
KVEWE = T685-KVEWE AND
KAPPL = T685-KAPPL AND
KSCHL = T685-KSCHL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVMM_MAP_COND-VTEXT =
T685T-VTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVMM_MAP_COND-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVMM_MAP_COND-VTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVMM_MAP_COND USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVMM_MAP_COND-GRUPO TO
ZTMM_MAP_COND-GRUPO .
MOVE ZVMM_MAP_COND-KSCHL TO
ZTMM_MAP_COND-KSCHL .
MOVE ZVMM_MAP_COND-MANDT TO
ZTMM_MAP_COND-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTMM_MAP_COND'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTMM_MAP_COND TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTMM_MAP_COND'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVMM_MAP_COND USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTMM_MAP_COND-MANDT =
ZVMM_MAP_COND-MANDT .
ZTMM_MAP_COND-GRUPO =
ZVMM_MAP_COND-GRUPO .
ZTMM_MAP_COND-KSCHL =
ZVMM_MAP_COND-KSCHL .
ZTMM_MAP_COND-METODO =
ZVMM_MAP_COND-METODO .
ZTMM_MAP_COND-CALCULA =
ZVMM_MAP_COND-CALCULA .
    SELECT SINGLE * FROM T685 WHERE
KVEWE = 'A' AND
KAPPL = 'TX' AND
KSCHL = ZTMM_MAP_COND-KSCHL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T685T WHERE
KVEWE = T685-KVEWE AND
KAPPL = T685-KAPPL AND
KSCHL = T685-KSCHL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVMM_MAP_COND-VTEXT =
T685T-VTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVMM_MAP_COND-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVMM_MAP_COND-VTEXT .
    ENDIF.
ENDFORM.
