FUNCTION-POOL zfgmm_alivium.                "MESSAGE-ID ..

* INCLUDE LZFGMM_ALIVIUMD...                 " Local class definition

CONSTANTS: gc_s_bus_place TYPE te_struc VALUE 'ZALIVIUMBUS_PLACE'.

CONSTANTS: gc_blart         TYPE blart VALUE 'SA',
           gc_processo      TYPE ze_alivium_processo VALUE 'ACABADO',
           gc_bwart         TYPE bwart VALUE 702,
           gc_grupo         TYPE ze_alivium_grupo VALUE 'STOCK',
           gc_currency      TYPE waers VALUE 'BRL',
           gc_inco1         TYPE inco1 VALUE 'CIF',
           gc_rate          TYPE c VALUE 'R',
           gc_value         TYPE c VALUE 'V',
           gc_auart_saida   TYPE auart VALUE 'ZAJS',
           gc_auart_entrada TYPE auart VALUE 'ZAJE',
           gc_90            TYPE c LENGTH 2 VALUE '90'.

CONSTANTS: BEGIN OF gc_cond,
             icmi TYPE kscha VALUE 'ICMI',
             ists TYPE kscha VALUE 'ISTS',
             icbs TYPE kscha VALUE 'ICBS',
             ipbs TYPE kscha VALUE 'IPBS',
             ipva TYPE kscha VALUE 'IPVA',
             icva TYPE kscha VALUE 'ICVA',
             bco1 TYPE kscha VALUE 'BCO1',
             bco2 TYPE kscha VALUE 'BCO2',
             bpi1 TYPE kscha VALUE 'BPI1',
             bpi2 TYPE kscha VALUE 'BPI2',
             bx10 TYPE kscha VALUE 'BX10',
             bx11 TYPE kscha VALUE 'BX11',
             bx12 TYPE kscha VALUE 'BX12',
             bx13 TYPE kscha VALUE 'BX13',
             bx16 TYPE kscha VALUE 'BX16',
             bx20 TYPE kscha VALUE 'BX20',
             bx21 TYPE kscha VALUE 'BX21',
             bx22 TYPE kscha VALUE 'BX22',
             bx23 TYPE kscha VALUE 'BX23',
             bx40 TYPE kscha VALUE 'BX40',
             bx41 TYPE kscha VALUE 'BX41',
             bx42 TYPE kscha VALUE 'BX42',
             bx43 TYPE kscha VALUE 'BX43',
             bx70 TYPE kscha VALUE 'BX70',
             bx71 TYPE kscha VALUE 'BX71',
             bx72 TYPE kscha VALUE 'BX72',
             bx80 TYPE kscha VALUE 'BX80',
             bx81 TYPE kscha VALUE 'BX81',
             bx82 TYPE kscha VALUE 'BX82',
             bx9m TYPE kscha VALUE 'BX9M',
             isfr TYPE kscha VALUE 'ISFR',
             bx9i TYPE kscha VALUE 'BX9I',
             bx9l TYPE kscha VALUE 'BX9L',
             isfb TYPE kscha VALUE 'ISFB',
             bx4b TYPE kscha VALUE 'BX4B',
             bx4c TYPE kscha VALUE 'BX4C',
             bx4a TYPE kscha VALUE 'BX4A',
           END OF gc_cond,

           BEGIN OF gc_condtype,
             b TYPE krech VALUE 'B',
           END OF gc_condtype,

           BEGIN OF gc_taxtyp,
             icon TYPE j_1btaxtyp VALUE 'ICON',
             icm1 TYPE j_1btaxtyp VALUE 'ICM1',
             ipsn TYPE j_1btaxtyp VALUE 'IPSN',
             icsc TYPE j_1btaxtyp VALUE 'ISCS',
             icfp TYPE j_1btaxtyp VALUE 'ICFP',
             ics3 TYPE j_1btaxtyp VALUE 'ICS3',
             icm3 TYPE j_1btaxtyp VALUE 'ICM3',
             ipi1 TYPE j_1btaxtyp VALUE 'IPI1',
             ipi3 TYPE j_1btaxtyp VALUE 'IPI3',
           END OF gc_taxtyp.

DATA: gt_zalivium_params TYPE TABLE OF ztmm_alivium_par,
      gs_zalivium_params TYPE ztmm_alivium_par.
