"Name: \PR:SAPLMEPO\FO:MEPO_ITEMS_FILL_CUSTOMFIELDS\SE:END\EI
ENHANCEMENT 0 ZMMEI0019.
*Pedido de insumo com tipo de subcontratação
 IF EKPO-EMLIF IS NOT INITIAL AND
    EKPO-PSTYP EQ '0' AND
   ( EKPO-SERRU EQ 'X' OR EKPO-SERRU EQ 'Y' ).
   FEKPO-SERRU = EKPO-SERRU.
 ENDIF.
ENDENHANCEMENT.
